version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: streamlive-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streamlive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
#  rtmp:
#    image: tiangolo/nginx-rtmp
#    container_name: streamlive-rtmp
#    ports:
#      - "1935:1935"  # RTMP порт для входящего потока
#      - "8088:80"     # HTTP порт для HLS
#    volumes:
#      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf:ro
#      - rtmp_data:/var/www/html/hls
#    restart: unless-stopped
#

  rtmp:
    image: tiangolo/nginx-rtmp
    container_name: streamlive-rtmp
    ports:
      - "1935:1935"  # RTMP порт для входящего потока
      - "8088:80"     # HTTP порт для HLS
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf:ro
      - rtmp_data:/var/www/html/hls
    restart: unless-stopped

volumes:
  postgres_data:
  rtmp_data:
